[package]
name = "tigr"
version = "0.1.0"
authors = ["k-nasa <htilcs1115@gmail.com>"]
edition = "2018"

[dependencies]
rust-ini = "0.13"
ruspec = "0.1.3"
failure = "*"
clap = "*"
flate2 = "1.0"
sha1 = "0.6.0"
